### PR TITLE
Improve calculation of local cache expiration

### PR DESCRIPTION
**Pull request by maxiberta**
This seems to fix the gargoyle multiprocess sync issue mentioned in https://github.com/YPlan/gargoyle/issues/83.

### CODE REVIEW

**Comment by adamchainz** [comment]
I know it's tricky with multiprocess/thread stuff, but can you think of a test to add?

**Comment by adamchainz** [comment]
Also please add a line to HISTORY.rst

**Comment by maxiberta** [comment]
Added a unit test where I tried to reproduce the abovementioned issue in as few steps as possible.

**Comment by adamchainz** [comment]
Merged in 83a9609325196dae71309ecf2124f6abfea67e58, thanks!

The code structure of `CachedDict` is way too confusing, it could do with a general refactor.

**Comment by adamchainz** [comment]
Deployed on PyPI: https://pypi.python.org/pypi/django-modeldict-yplan

**Pull request closed without merging**
